### ISSUE TITLE
why express module name with '' ?

### ISSUE THREAD

**Issue by pdincau** [mobos/mob#1]
```
https://github.com/mobos/mob/blob/master/apps/mob/src/mob_app.erl#L12
```

**Comment by 0xNaN** [comment]
hi,
the answer is simple: the initial app template (which include `mob_app.erl`) has been made using `rebar3 new release` command and this the way rebar3 did it :smiley:  probably because this allows any name (also with special chars) to be used as release name (see chapter 3.3 http://erlang.org/doc/reference_manual/data_types.html).

For the module name `mob_sup` there is no need for "'" but it stayed untouched until now, we will be grateful if you make a little pull request!

**Comment by pdincau** [comment]
here you are: https://github.com/mobos/mob/pull/3
